/********************************************************************************************
* Name      : LocationTracingHelper
* Purpose   : Helper to LocationTracingTriggerHandler
* Author    : Bruna Girão
* Date      : 22/03/2022
-------------------------------------------------------------------------------------------
22/03/2022           Bruna Girão         create class 
********************************************************************************************/
public with sharing class LocationTracingHelper {

}
